#!/usr/bin/env python3
"""Build the Case Response Drafter outputs from src/.

Outputs (in dist/):
  dashboard.html                      - Cowork live artifact (needs the Cowork Salesforce bridge)
  Case-Response-Drafter-Offline.html  - standalone page, no network, works in any browser
  lib.cjs                             - shared logic as a Node module (used by the CLI and tests)

Usage:  python3 tools/build.py
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")
DIST = os.path.join(ROOT, "dist")


def read(*p):
    with open(os.path.join(*p), encoding="utf-8") as f:
        return f.read()


def write(path, text):
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"  wrote {os.path.relpath(path, ROOT)}  ({len(text)//1024} KB)")


shared = read(SRC, "shared.js")
app = read(SRC, "app.js")
offline = read(SRC, "offline.js")
both = shared + "\n" + app

# Functions/constants the offline page and Node lib reuse. Later definitions win, matching browser behaviour.
LIB_CONSTS = ["SIGN_TXT", "MON_TXT", "MONTHS", "STAGE_TO_TYPE"]
LIB_FUNCS = ["esc", "decode", "parseRecords", "classify", "slim", "utcDateStr", "scrub", "alertType",
             "clusterOf", "plusDays", "facts", "impactFor", "nextStepFor", "templateDraft",
             "rubrikSinceCustomer", "ordinal", "autoType", "firstSentence", "promisedDate", "nameFrom",
             "localSummary"]


def extract_fn(name):
    starts = [m.start() for m in re.finditer(r"(?m)^(async\s+)?function " + re.escape(name) + r"\(", both)]
    if not starts:
        raise SystemExit(f"build error: function {name} not found")
    i = starts[-1]
    line = both[i:both.index("\n", i)]
    if "{" in line and line.count("{") == line.count("}"):
        return line + "\n"
    return both[i:both.index("\n}\n", i) + 3]


def extract_const(name):
    i = both.index("const " + name + " ")
    line = both[i:both.index("\n", i)]
    if line.rstrip().endswith(";") and line.count("{") == line.count("}"):
        return line + "\n"
    return both[i:both.index("\n};", i) + 3] + "\n"


lib = ("// Shared logic for the Case Response Drafter (generated by tools/build.py - edit src/, not this file).\n"
       + "".join(extract_const(c) for c in LIB_CONSTS) + "\n"
       + "\n".join(extract_fn(f) for f in LIB_FUNCS))
for banned in ("callMcpTool", "askClaude"):
    if banned in lib:
        raise SystemExit(f"build error: offline lib must not contain {banned}")

os.makedirs(DIST, exist_ok=True)
print("Building…")
dashboard = read(SRC, "templates", "dashboard.template.html").replace("/*SHARED*/", shared).replace("/*APP*/", app)
write(os.path.join(DIST, "dashboard.html"), dashboard)

offline_html = read(SRC, "templates", "offline.template.html").replace("/*LIB*/", lib).replace("/*OFFLINE*/", offline)
if "callMcpTool" in offline_html or "askClaude" in offline_html:
    raise SystemExit("build error: offline page must not make network/AI calls")
write(os.path.join(DIST, "Case-Response-Drafter-Offline.html"), offline_html)

OFFLINE_FUNCS = ["parseCSV", "toIso", "parseThread", "parseInput", "dateStr", "noteField", "hello",
                 "extraTemplate", "buildDraft", "resolutionDetails", "iqsCheck"]


def extract_from(text, name):
    m = re.search(r"(?m)^function " + re.escape(name) + r"\(", text)
    if not m:
        raise SystemExit(f"build error: offline function {name} not found")
    i = m.start()
    line = text[i:text.index("\n", i)]
    if "{" in line and line.count("{") == line.count("}"):
        return line + "\n"
    return text[i:text.index("\n}\n", i) + 3]


offline_lib = "\n".join(extract_from(offline, f) for f in OFFLINE_FUNCS)
LIB_FUNCS_ALL = LIB_FUNCS + OFFLINE_FUNCS
node_lib = ("'use strict';\n"
            "// Minimal DOM shim so decode() works in Node.\n"
            "const _ent = { '&nbsp;':' ', '&amp;':'&', '&lt;':'<', '&gt;':'>', '&quot;':'\"', '&#39;':\"'\", '&times;':'×' };\n"
            "const document = (typeof globalThis.document !== 'undefined') ? globalThis.document : { createElement: () => ({ set innerHTML(v){ this._v = String(v).replace(/&[a-z#0-9]+;/gi, m => _ent[m] || (m.startsWith('&#') ? String.fromCharCode(parseInt(m.slice(2), 10)) : m)); }, get value(){ return this._v; } }) };\n"
            + lib + "\n" + offline_lib +
            "\nmodule.exports = { " + ", ".join(LIB_FUNCS_ALL + LIB_CONSTS) + " };\n")
write(os.path.join(DIST, "lib.cjs"), node_lib)
print("Done.")
